spring:
  application:
    name: "bClavis"
  config:
    # VMoption에 설정한 변수를 가져올 수 있음
    import: "optional:file:./secret.yml"
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:file:./test;MODE=MySQL;AUTO_SERVER=TRUE;OLD_INFORMATION_SCHEMA=TRUE;
    driverClassName: org.h2.Driver
    username: sa
    password: 1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: false
    hibernate.ddl-auto: update


